### ISSUE TITLE
Example script to override overworld?

### ISSUE THREAD

**Issue by resinate** [maruohon/justenoughdimensions#10]
is there a way you can provide a custom script for overriding the overworld. im having issues making it work.
i havent seen any tut videos on it

**Comment by maruohon** [comment]
Do you use Discord? If you do, we could talk about this on my server here: https://discorg.gg/2FgywHj

If not, then could you describe what you are trying to accomplish exactly? Overriding the overworld (dimension 0) has a lot more potential for problems that just using custom dimensions. So I'd usually recommend trying to find a way to do what you want by using custom dimensions, possibly initial spawn dimension overriding etc. first.

But if you need to override the overworld, all you should need is two things (in addition to creating any other custom dimension):
* Enable dimension overriding in the main `justenoughdimensions.cfg` config file (or via the in-game config menu in single player)
* Add the `"override": true` key/value on the main level of the dimension's entry in the `dimensions.json` config for dimension 0. Of course you will then also need to have the dimensiontype values etc. set according to the type of dimension you want it to be.

**Comment by resinate** [comment]
yea thats what i dont get thats why i was asking for a quick example so i can learn off it lol im on discord tho
