### ISSUE TITLE
Suggestion: Add a link for a Json Editor to the documentation for the mod.

### ISSUE THREAD

**Issue by Winddbourne** [maruohon/justenoughdimensions#12]
I've been having fun playing with the dimension configurations but I started out using a text editing program to edit my Json files. It worked very well for a systems oriented autistic but there were a few problems I ran into. Namely when I got an error none of the line or column values lined up and it led me on more than one wild goose chase before I realized I wasn't using the proper tool.

Once I looked up this free Json editor online , "http://www.cleancss.com/json-editor/", the messages I was seeing in the log became a lot more useful, plus the editor itself would show me where my code had an issue as best it could. 

So the log would say "unclosed object at line 9 column 24" or something similiar and it was easy to see I forgot a comma after a string on line 23. I still don't know what "Expected name" means but nothing is perfect. 

I'm thinking a lot of people would be helped by having the proper viewer available to spot bugs easily right form the start. :)

**Comment by maruohon** [comment]
I finally got around to adding some of these editor and validator links to the documentation/CurseForge page.
