### ISSUE TITLE
Setting a dim to only use one biome not working

### ISSUE THREAD

**Issue by MechWarrior99** [maruohon/justenoughdimensions#2]
I copy and pasted your example scripts of how to do it but it did not work, I trieda couple of other things(like using the id instead of the name). But it didn't work. help 
{  
    "dimensions": [  
        {  
            "dim": 9,
            "dimensiontype":{
                "id": 9,
                "name": "Test dim 9",
                "suffix": "dim9",
                "keeploaded": false,
                "worldprovider": "WorldProviderHellJED"
            },
			"worldinfo": {}
        },
		{
      "dim": 8,
      "biome": "desert",
      "dimensiontype": {
        "id": 8,
        "name": "Test Dim 8",
        "suffix": "_dim8",
        "keeploaded": false,
        "worldprovider": "WorldProviderSurfaceJED"
      },
      "worldinfo": {
        "JED": {
          "ForceGameMode": true,
          "SkyColor": "99ff99",
          "FogColor": "bbbbff",
          "SkyRenderType": 1,
          "SkyDisableFlags": 0
        }
      },
      "worldinfo_onetime": {
        "RandomSeed": "Not Foo Bar",
        "GameType": 1
      }
    }
	]
}

Minecraft: 1.10.2
JED: 1.3.3

**Comment by maruohon** [comment]
Did you also remember to enable the **enableOverrideBiomeProvider** option in the main mod config (for example via the in-game config menu, or in the justenoughdimensions.cfg file)?

And the entry in the dimensions.json does need to be the biome's registry name, an ID will not work.
You can get a list of all registered biomes with the biome dump command in the TellMe mod.
For all vanilla biomes, here is an example dump: http://pastebin.com/raw/U5cvkdKz
So you want hat is in the **Registry name** column. For vanilla biomes you can omit the 'minecraft:' prefix, but for any mod biomes you need to give the entire registry name.

**Comment by MechWarrior99** [comment]
Yeah, sorry. I forgot to enable the biome override. Thanks for the help and the mod suggestion. (I did figure that IDs would not work, but I figured I would try on the off chance.)
