### ISSUE TITLE
Dimension Name is not working

### ISSUE THREAD

**Issue by davqvist** [maruohon/justenoughdimensions#25]
Here my custom dimensions: https://pastebin.com/0kdAVq0Z

Using /forge tps shows for dimensions 1100 and 1101 the dimension nme "JED Surface 0" instead of their respective names. Not tested for the others, but they are probably not working either. I also tested with DimensionType.getById( id ).getName() with my mod and it throws an exception, meaning the name is not set. It worked in JED 1.5.0, pretty confident on that.

MC 1.12.2
Forge 2654
JED 1.6.0-dev.20180411.215951

**Comment by davqvist** [comment]
Thanks for your elaborate explanation, but I have trouble understanding that all. To be precise: What are the downside if I use "require_exact_match": true in my configuration?

**Comment by maruohon** [comment]
In most cases probably nothing. Basically that option alone will cause JED to register the entries when it loads the config, which should be early enough to not cause issues, at least in single player. I'm not entirely sure whether or not that would lead to the Optifine crash on a server though... although... I think I'm syncing the dimensions on initial join to the server? In which case it shouldn't cause issues unless the player joins another server with a different dimension configuration, without restarting the game.

So basically I'm pretty sure in most cases you are fine enabling that. The older way JED worked was that it *always* registered new entries when (re-)loading the configuration, even if there would have already been identical entries registered. Now it uses existing entries whenever possible, according to the three options that control it (ie. whether it finds a suitable existing entry). So the `force_register` (oh god why is there a typo in the pastebin on that one?! >_>) option is what would get you into  trouble at least with Optifine, if you were to save & exit and then reload a world in single player, or I think also if re-joining a server, maybe(?).

**Comment by davqvist** [comment]
Thanks, I will try with require_exact_match

**Comment by davqvist** [comment]
Works, thanks
