### ISSUE TITLE
JED crash with Sponge

### ISSUE THREAD

**Issue by DarkmoreSOS** [maruohon/justenoughdimensions#28]
JED will generate a world with out crashing using forge. But JED will crash generating a new world with sponge forge. The mod will not crash when there is no JSON or a config file.
Forge 14.23.3.2655
Sponge 1.12.2-2655-7.1.0-BETA-3072
JED 1.12.2-1.6.0-dev.20180502.030835
Crash log
https://pastebin.com/MnWZJr7E

**Comment by maruohon** [comment]
Fixed in `justenoughdimensions-1.12.2-1.6.0-dev.20180514.212017.jar`.
