### ISSUE TITLE
[1.12.2] Dimension conflict with Advanced Rocketry and TechReborn

### ISSUE THREAD

**Issue by TheSnowyChickens** [maruohon/justenoughdimensions#33]
1.12.2
justenoughdimensions-1.12.2-1.6.0-dev.20180619.124018
Forge 2739
TechReborn-1.12.2-2.16.0.746-universal
AdvancedRocketry-1.12.2-1.4.0-92-universal

Hello,
I have some problems with my dimension.

Config screen:
![grafik](https://user-images.githubusercontent.com/29357962/43147743-039909cc-8f64-11e8-85a6-d6994646fa40.png)

Now what is happend:
It should be a Biomes'o Plenty dimension, with ID 10, but the dimension is a TechReborn Wasteland Dimension with Advanced Rocketry Biomes and sky.
(In the world folder I didn't found a folder with "Dim10", but "Dim4598" <- TechReborn)

I joined the world with "/tpj 10".

This is on a Server, but I configurated it in Singleplayer.

**Comment by TheSnowyChickens** [comment]
1. Yes, there is no Dim10 in my world folder.
2. I cant find any other Dim10 register in my configs.
3. 
![grafik](https://user-images.githubusercontent.com/29357962/43149243-48287f70-8f67-11e8-940d-f8f9d9df9994.png)

4. No Sponge. Just Forge and 151 Mods.

**Comment by maruohon** [comment]
Can you check what it printed to the game console, that output is a lot more informative. You should get something like this:
```
[INFO] +-----+---------+---------------+-------------+-------------------------+---------+
[INFO] |  ID | Type ID | Name          | Load Spawn? | WorldProvider class     | Loaded? |
[INFO] +-----+---------+---------------+-------------+-------------------------+---------+
[INFO] |   0 |       0 | overworld     |        true | WorldProviderSurface    |    true |
[INFO] |  -1 |      -1 | the_nether    |       false | WorldProviderHell       |   false |
[INFO] |   1 |       1 | the_end       |       false | WorldProviderEnd        |   false |
[INFO] | 123 |     123 | Old overworld |       false | WorldProviderSurfaceJED |   false |
[INFO] +-----+---------+---------------+-------------+-------------------------+---------+
[INFO] |  ID | Type ID | Name          | Load Spawn? | WorldProvider class     | Loaded? |
[INFO] +-----+---------+---------------+-------------+-------------------------+---------+
```

**Comment by TheSnowyChickens** [comment]
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: +------+---------+--------------+-------------+------------------------+---------+
-- | -- | -- | -- | --
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   ID \| Type ID \| Name         \| Load Spawn? \| WorldProvider class    \| Loaded? \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: +------+---------+--------------+-------------+------------------------+---------+
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    0 \|       0 \| overworld    \|        true \| WorldProviderSurface   \|    true \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    1 \|       1 \| the_end      \|       false \| WorldProviderEnd       \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   -1 \|      -1 \| Nether       \|       false \| WorldProviderBOPHell   \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|  418 \|     418 \| tartarus     \|       false \| WootWorldProvider      \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \| 4598 \|    4598 \| nc_wasteland \|        true \| WorldProviderWasteland \|    true \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   -2 \|       3 \| space        \|       false \| WorldProviderSpace     \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    2 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    4 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    5 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    6 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    7 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    8 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|    9 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   10 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   11 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   12 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   13 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   14 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   15 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   16 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   17 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   18 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   19 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   20 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   21 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   22 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   23 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   24 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   25 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   26 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   27 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   28 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   29 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   30 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   31 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   32 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   33 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   34 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   35 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   36 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   37 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   38 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   39 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   40 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   41 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   42 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   43 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   44 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   45 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   46 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   47 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   48 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   49 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   50 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   51 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   52 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   53 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   54 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   55 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   56 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   57 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   58 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   59 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   60 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   61 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   62 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   63 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   64 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   65 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   66 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   67 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   68 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   69 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   70 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   71 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   72 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   73 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   74 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   75 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   76 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   77 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   78 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   79 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   81 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   82 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   83 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   84 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   85 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   86 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   87 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   88 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   89 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   90 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   91 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   92 \|       2 \| planet       \|       false \| WorldProviderPlanet    \|   false \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: +------+---------+--------------+-------------+------------------------+---------+
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: \|   ID \| Type ID \| Name         \| Load Spawn? \| WorldProvider class    \| Loaded? \|
19:51:46 | game |   | info | [17:51:46] [Server thread/INFO] [justenoughdimensions]: +------+---------+--------------+-------------+------------------------+---------+

**Comment by TheSnowyChickens** [comment]
The log in  a better view.^^ +more
[Log.txt](https://github.com/maruohon/justenoughdimensions/files/2224417/Log.txt)

**Comment by maruohon** [comment]
(Cleaned up version: https://pastebin.com/raw/n1QXPyQZ ).

So yeah you seem to have a TON of Advanced Rocketry dimensions, including the ID 10 used by it. So you'd probably want to select another ID, unless you specifically wanted to override that planet with JED? If so, then you need to enable the dimension override option in the main JED config, and then add a `"override": true` option to the `dimensions.json` at the "top level" of the dimension entry, like so: https://pastebin.com/JDRzMELN

**Comment by TheSnowyChickens** [comment]
Oh okay, 
I could not see more then a few dimension ID's in the A.R. config, so I thought 10 is free. :D 

Finally I can only say, thank you for the fast help and the solution of the problem. 👍

**Comment by maruohon** [comment]
You're welcome.

Using the `/jed list-registered-dimensions` and/or the `/jed list-loaded-dimensions` commands can be really useful when checking for what is actually registered in the game. And also the `/jed debug` command when run in a given dimension will give you a bunch of information about that dimension, which would help with figuring out what properties the dimension actually has and how it was registered (or by what mod, possibly).
