### ISSUE TITLE
SkyDisableFlags not working

### ISSUE THREAD

**Issue by clubpetey** [maruohon/justenoughdimensions#38]
Using the dimensions.json config below, I would expect my sky to have no moon/stars and a purple background/haze.  What's I'm seeing is the moon and stars and a black background.

https://pastebin.com/qDSL5nNq

**Comment by maruohon** [comment]
You have at least a trailing comma on line 91, which would break parsing the config.

**Comment by clubpetey** [comment]
Removed the comma, but same issue.  It's possible some other Mod is over-writing the sky, Astral Sorcery and Thaumcraft Could be the culprits.  But I specifically disabled AS in this dimension.

**Comment by clubpetey** [comment]
debug did the trick. Turns out I am a complete idiot and forgot that I reverted back to 1.5.5 to test something and forget about the config changes, swiching back to beta-1.6.0 fixed the hiding of the stars/moon/sun.

The colors were not appear because I had set the time to 18000 because I wanted a low light level (day/night cycle is off).  But I guess if you set the time to night, you get black all the time.  I would have liked to have the color override the night sky (maybe darkened though) rather than force night to be black, but this may be intended behavior.

I will close this now, but let me know if there a way to change the night sky colors.

**Comment by maruohon** [comment]
I added a new JED option `SkyLightBlend` to define the blend ratio of the sky color with the light level. The horizon/fog still looks a bit funny at night, but it's still quite good compared to the old complete blackness.

Blend ratio 1.0 (old behavior):
![2019-01-01_20 53 42](https://user-images.githubusercontent.com/2331050/50575397-8aef2880-0e07-11e9-9aa5-8cc71b123f58.png)

Blend ratio 0.0 during day, with the fog color set to the same color as the sky (`30F0F0`):
![2019-01-01_20 51 41](https://user-images.githubusercontent.com/2331050/50575405-9b9f9e80-0e07-11e9-8a74-d3fdeb54bc16.png)

Blend ratio 0.0 during night:
![2019-01-01_20 51 53](https://user-images.githubusercontent.com/2331050/50575413-cb4ea680-0e07-11e9-8e79-e30d6bb6e51b.png)

**Comment by clubpetey** [comment]
That looks great, I'm sure I can fiddle with the sky/fog color to get the right level of creepiness I'm looking for.  Plus now that I can set night, Dynamic Sound gives me all the night ambiance... Sweet.
