### ISSUE TITLE
[Compatibility] Lost city Biospheres spawn and Just Enough Dimensions

### ISSUE THREAD

**Issue by sadface-0** [maruohon/justenoughdimensions#41]
When i have Just Enough Dimensions installed, i am unable to force the spawn inside sphere via the lost city profile config option <in>. If i disable just enough dimensions, it works fine. 

Was hoping this could be fixed as i would love to get the best of both worlds. Thank you!

**Comment by maruohon** [comment]
Does Lost Cities normally handle the spawn point, I assume so? You should be able to disable JED's spawn point search/override like in this example config: https://pastebin.com/2dJNFfcR (the `SpawnPointSearchType` bit). This only works in some of the latest 1.6.0 beta versions.

**Comment by sadface-0** [comment]
Hello,

I am using lost cities bop as my overworld, and currently have no entries in dimensions.json (for testing).

 In the lost cities' biosphere profile config, you can specify spawn to be inside a sphere using <in>, it stops working when i have JED enabled, even with a lot of the JED config options set to false. I have not yet tried registering the overworld with an override with the spawn config option you posted, I'll be able to test it tonight after work.

**Comment by maruohon** [comment]
Oh, well that is very strange then indeed... JED isn't supposed to affect anything for a dimension if you don't have anything configured for that dimension. I'll need to try it out and try to figure out what's going on then. Can you post the Lost Cities configs and stuff you are using, so I can try to reproduce it with the same configs?

**Comment by sadface-0** [comment]
Unfortunately, I was not able to get the `SpawnPointSearchType` working.
For troubleshooting & demonstration, I went ahead and created a new modpack project to test the issue, and it still exists.

Mods Used:
![image](https://user-images.githubusercontent.com/11811815/54590482-90a1f500-4a6b-11e9-9fe9-8b90cb1a152f.png)

All config options were left default with the exception of \config\lostcities\profile_biosphere.cfg

profile_biosphere.cfg (https://pastebin.com/mzS0grAR) has been edited to match the concept I'm hoping to achieve.
Line 379 Change:    S:spawnBiome=
Line 388 Change:     S:spawnSphere=<in>



**If I disable Just Enough Dimensions, it works fine (spawn in sphere) as outlined below:**
![image](https://user-images.githubusercontent.com/11811815/54590916-7d435980-4a6c-11e9-8b63-482fd6e171d7.png)
![image](https://user-images.githubusercontent.com/11811815/54591036-afed5200-4a6c-11e9-8edd-35f74dd8a777.png)


**If I enable Just Enough Dimensions, I spawn outside of sphere (outlined below):**
![image](https://user-images.githubusercontent.com/11811815/54591142-f2af2a00-4a6c-11e9-9e06-a4cc17320c69.png)
![image](https://user-images.githubusercontent.com/11811815/54591219-25592280-4a6d-11e9-8540-cbfe5aac03d5.png)

**Comment by maruohon** [comment]
I just uploaded a new build to CurseForge, which rewrites some of how the spawn point search stuff in JED works. Basically it doesn't forcibly search for an overworld spawn point anymore, fixing this issue.

**Comment by sadface-0** [comment]
Verified that it is working. Thank you for your fast action on this!! :D
