### ISSUE TITLE
Skybox of the custom dimensions are no compatible with AR.

### ISSUE THREAD

**Issue by eagleyes005** [maruohon/justenoughdimensions#45]
Basically when I create a dimension with the JED and make it become a planet the sky simply remains the same as the vanilla. I talked to the Advanced Rocketry devs and they said that the JED dimension skybox overide everything (because the sky color and other things). Is there a way to make a custom Skybox option to dimensions that allows me to use the AR one?

**Comment by maruohon** [comment]
How does AR do the sky rendering? Do they have their own SkyRenderer class? If so, you should be able to use that via JED. Otherwise I'm not sure what you/they mean by "JED skybox overriding everything", a normal custom JED dimension simply uses JED's WorldProvider, it doesn't otherwise override anything. Can you link me to that discussion with the AR dev?

**Comment by eagleyes005** [comment]
Unfortunately not because I spoke with them through discord. Btw i think they have they own Skyrender, since they need to make the sky look diferent as the planet is farther or closer to the sun, it can have more then one moon or be closer to another planet too. 
So is there a way to support this custom SkyRenderer class?

**Comment by maruohon** [comment]
There are no "sky setting to turn off" in JED.

But try if this would work (basically you just need that `SkyRenderer` JED option): https://pastebin.com/6p27vijj
This should cause that dimension to use AR's sky renderer, The other renderer class name is in the "comment" on the second line, I don't know which renderer you would like to use?

**Comment by eagleyes005** [comment]
Ok, i will try both and see if it works. 
For now thank you so much. :)

**Comment by eagleyes005** [comment]
Works really fine to me!
