### ISSUE TITLE
Major Request - Some Simple Presets

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [maruohon/justenoughdimensions#5]
Well I have to ask this because I am not a skilled user of command line and I am interested in a multidim server. Simple dimensions has a gui that mimics Vanilla GUI Could you add a similar function? Lumien is often gone and I can never seem to get my bug reports answered and you and I have worked before. Please it would mean the world to me. 

PS:I am freaking excited for 1.12 and 1.13.

**Comment by maruohon** [comment]
Adding a fully featured GUI for editing all aspects of the dimensions would be quite the amount of work, especially if it should also work in multiplayer. I'm quite swamped with other projects and also IRL stuff that should get done, so I'd say this is unlikely to happen, at least in the short term. (The mod as it is currently, is really meant to be configured through the dimensions.json config file. The in-game dimbuilder command can also achieve most things, but currently it at least can't change the per-dimension gamerules.)

However if there are specific things that the documentation on the CurseForge page doesn't cover, or if more examples of certain things are needed, then I'm happy to improve the documentation. Or if you simply have questions on how to achieve certain things for the dimensions, then feel free to ask, and I can give you some example configs.

**Comment by P3rf3ctXZer0** [comment]
Could you make me a preset then? Simply put I want all ores even modded ores to be able to spawn from level 0 - 255 and sea level to be 74 Basically I want a flooded world island adventure. If you can't though understand.

**Comment by maruohon** [comment]
Most of those requirements don't really have much to do with the dimension itself, and thus they aren't really JED-specific.

* Ore generation heights are dependant on the ore generator, so whichever mod is generating them, needs to be configured to allow them to generate at any height. I'm not familiar with the vanilla world generation settings really, I think it allows for customization of the vanilla ores though (assuming that vanilla is the one that generates those ores in your pack), so I'll need to look into that.
* Sea level setting I'm not that familiar with either, what actually controls that... I'll need to look into that. It may be the world generation settings again?
* What do you mean by "all biomes with Biomes O' Plenty support"?
* A skyland world needs some sort of custom world generator that can do that type of worlds. Again, JED itself has no world generators...
* A void dimension can be made using the vanilla superflat generator. If you want one block there, it can be placed using the vanilla setblock command, like so: `/setblock 0 0 0 minecraft:stone` (from the top of my head, not entirely sure about the argument order, the command help will tell you if this doesn't work). I can get you an example config for this tomorrow (I'll edit this comment).

**Comment by maruohon** [comment]
Well it took a couple of days before I got around to this... but here is a config with a void world example (dim 8), and a "water world" example (dim 9), where the sea level has been set to y = 99.

https://pastebin.com/EE2UcVzn

**Comment by P3rf3ctXZer0** [comment]
yay thank you :)
