### ISSUE TITLE
Dimensions not registering on server

### ISSUE THREAD

**Issue by mtc52** [maruohon/justenoughdimensions#50]
I made two simple custom dimensions that work fine on single player, but are not registering on my Minecraft server.  The justenoughdimensions.cfg is set to the defaults (version 1.6.0 for Minecraft 1.12.2) and I am using forge 14.23.5.2847.

The Dimensions.json looks like this:

{
    "dimensions": [
        {
            "dim": 2,
			"biome": "minecraft:ice_flats",
            "dimensiontype": {
                "id": 2,
                "name": "Frost Dimension",
                "worldprovider": "WorldProviderSurfaceJED",
                "require_exact_match": true
            },
			
            "worldinfo_onetime": {
                "DayTime": 18000,
                "GameRules": {
                    "doDaylightCycle": "false"
                }
            },
            "jed": {
                "SkyRenderType": 1,
                "SkyDisableFlags": 7,
                "CloudRenderer": "DummyRenderer",
                "SkyBlend": 1.0,
                "DisableDawnDuskColors": true,
                "SkyColor": "000000",
                "FogColor": "000000"
            }
        },
		{
            "dim": 3,
			"biome": "minecraft:desert",
            "dimensiontype": {
                "id": 3,
                "name": "Flame Dimension",
                "worldprovider": "WorldProviderSurfaceJED",
                "require_exact_match": true
            },
			
            "worldinfo_onetime": {
                "DayTime": 18000,
                "GameRules": {
                    "doDaylightCycle": "false"
                }
            },
            "jed": {
                "SkyRenderType": 1,
                "SkyDisableFlags": 7,
                "CloudRenderer": "DummyRenderer",
                "SkyBlend": 1.0,
                "DisableDawnDuskColors": true,
                "SkyColor": "000000",
                "FogColor": "000000"
            }
        }
    ]
}

**Comment by mtc52** [comment]
Not sure why the code block I copied and pasted looks weird, having trouble fixing it.  I did copy and paste the code into a json format checker to make sure the file is valid (it is).  Like I said in the original post, the dimensions register just fine in a single player world, but don't register on the server.

**Comment by maruohon** [comment]
Anything from JED in the server console or the log? You may need to enable the verbose logging option in the JED main config to get a bunch more debug output.

**Comment by maruohon** [comment]
Look earlier than that, there should be lines about JED loading the config file, and how many entries it parsed from it, and if it tries to register the dimensions.

**Comment by mtc52** [comment]
So the issue was that the dimensions.json wasn't loading correctly.  Turns out I had the file named Dimensions.json instead of dimensions.json.  I didn't realize that the filename was case sensitive.  After renaming the file and loading the world, the dimensions are working properly.  Thanks for the timely response, it probably would have taken me a lot longer to catch that without you pointing me to take a close look at the console.
