### ISSUE TITLE
TPJ goes to roof of nether

### ISSUE THREAD

**Issue by AlHollandiyah** [maruohon/justenoughdimensions#52]
I provided all of the dimensions in my json with a spawnX and spawnZ but no spawnY. In all of the dimensions that spawns me in a proper location with that X and Z, but in the nether it spawns me on the bedrock roof. I used worldedits /descend to find the next location below me, and put that as a Y value in the json, but maybe you could look in to why it does that, as there is plenty of space below Y128 to make a proper nether spawnpoint in all the cases where I tested it! Thanks!

**Comment by maruohon** [comment]
It's because in the default/overworld spawn point search type it selects the highest block at the given x/z column. There is a different spawn point search type, `cavern` that you can use for nether-type dimensions. An example of the usage of that is here: on lines 62-67 https://pastebin.com/d3EZzDY3

**Comment by AlHollandiyah** [comment]
Thats an option, but as I recall all the options within a "jed" tag recquire jed worldproviders. In this case the worldprovider is BOPHell, so I'm guessing that won't work in this case. So I'll probably just have to keep the SpawnY workaround in this case. Thanks either way!

**Comment by maruohon** [comment]
No, not all of them require a JED WorldProvider, this is one of the ones that doesn't. It's just stored within the same object that holds all the other options, most of which do require a JED WorldProvider. The config hierarchy maybe isn't the best it could be, for example to reflect which options would require the JED WorldProvider. But I also don't want to change it at this point as it would then break everyone's configs again.

**Comment by AlHollandiyah** [comment]
Yeah, that sounds like a pain. Good to know! Thanks!
