### ISSUE TITLE
Different Inventories over Dimensions

### ISSUE THREAD

**Issue by Petschko** [maruohon/justenoughdimensions#56]
Hey, I found this Mod and its super usefully! Thanks for the hard work

Sadly I have trouble get the "PlayerInventoryGroup" to work. I want to setup a Creative World were players can build in creative mode (Switching Gamemode), which works so far.
But I want that their survival Inventory stays in the survival dimensions and the Creative Inventory in the creative world.

You made an example how the inventory json should look like: https://pastebin.com/Lipi2hWu

My JSON looks like this, but it keeps the inventory over all worlds... Maybe because these are already existing worlds (Overworld, Nether, End etc)?

```json
{
  "config_version": {
    "id": "__default",
    "version": 0
  },
  "dimensions": [
    {
      "dim": -42,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": -1,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 0,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 1,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 4,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 10,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 50,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 51,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 52,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 53,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 418,
      "jed": {
        "PlayerInventoryGroup": "Survival"
      }
    },
    {
      "dim": 11,
      "dimensiontype": {
        "id": 11, 
        "name": "Art",
        "suffix": "_dim11",
        "keeploaded": false,
        "worldprovider": "WorldProviderSurfaceJED"
      },
      "worldinfo_onetime": {
        "generatorName": "flat",
        "GameType": 1,
        "MapFeatures": 0,
        "GameRules": {
          "commandBlockOutput": "false",
          "doDaylightCycle": "false",
          "doFireTick": "false",
          "doMobLoot": "false",
          "doMobSpawning": "false",
          "mobGriefing": "false",
          "doWeatherCycle": "false"
        }
      },
      "jed": {
        "PlayerInventoryGroup": "Creative",
        "ForceGameMode": true,
        "CanRespawnHere": false,
        "CanSleepHere": "deny",
        "CanSpawnHostiles": false,
        "CanSpawnPeacefulMobs": false,
        "RespawnDimension": 0
      }
    }
  ] 
} 
```

**Comment by maruohon** [comment]
Did you enable the per-dimension inventories feature in the JED main config? Some features, including this feature, have a main toggle option there.

Also you don't need to define the group for all dimensions, you can let the survival dimensions use the default group. Defining a different group for the creative dimension is enough, as that will then be different than the default group so the inventories will be swapped when moving between those groups.

**Comment by Petschko** [comment]
Ah awesome to know, I try it, I probably forgot to toggle it in the main config, I check it after cooking!

If its resolved I close this issue, thank you so much for the super fast reply! Do you accept donations?

**Comment by maruohon** [comment]
Yeah I should really steal the time from something else to update/write proper up-to-date documentation for JED at some point. There are lots of things that are not really explained anywhere, but I just explain it for anyone who asks or has issues with things...

There should be donation links on the CurseForge project pages, if you are rolling in so much extra cash that you need to give some of it to random people on the interwebs ;)

**Comment by Petschko** [comment]
Well Im fine with sometimes donation for helpful Projects, your project helps me about the most difficult thing people requesting from the server haha

But again, which option is it in the main config? I don't see any with inventory

**Comment by maruohon** [comment]
There should be a `B:enablePlayerInventoryGroups` option. Make sure you are using the latest 1.6.0 build, as I think it's only in the latest build.

**Comment by Petschko** [comment]
Yeah youre right! there is the config now with the latest build^^ My bad hehe

All works fine now, except the equipped baubles still can transferred over the dimensions. Not thaat much of a problem i think, since they cant equipped in creative mode

Now it works! Thank you^^

About the Baubles, you may should look into it. And about the config, it would help if you may just list every property like what can you put in which part if the json-objects. I think that could be enough of documentary, haha I always hate it to when doing code projects and i suck at it too ;)

**Comment by maruohon** [comment]
Hmm, Baubles slots were supposed to be handled. Doesn't look like there have been any new Baubles releases ether in a very long time...

**Comment by Petschko** [comment]
I make a new ticket with it, so its more clean for you~

**Comment by Petschko** [comment]
See here: https://github.com/maruohon/justenoughdimensions/issues/57
