### ISSUE TITLE
Failed to register dimension

### ISSUE THREAD

**Issue by Kirin92** [maruohon/justenoughdimensions#66]
I dunno why but every time I add something in the config file and want to register this dimension, it says:
Failed to register dimension from the config.
Is there a typo in my config? The json looks like this:

```
{
  "config_version": {
    "id": "__default",
    "version": 0
  },
  "dimensions": [
    {
      "dim": 5,
      "dimensiontype": {
        "id": 5,
        "name": "Farming",
        "suffix": "_dim5",
        "keeploaded": false,
        "worldprovider": "WorldProviderSurfaceJED"
      },
      "worldinfo_onetime": {
        "Difficulty": "1",
        "generatorName": "BIOMESOP"
		"RandomSeed": ""
      }
    },
	{
      "dim": 10,
      "dimensiontype": {
        "id": 10,
        "name": "Ikea",
        "suffix": "_dim10",
        "keeploaded": false,
        "worldprovider": "WorldProviderSurfaceJED"
      },
      "worldinfo_onetime": {
        "Difficulty": "0",
        "generatorName": "flat"
		"generatorOptions": "3;1*minecraft:bedrock,62*minecraft:dirt,1*minecraft:grass;1;"
		"RandomSeed": ""
      }
    }
	
  ]
}
```

**Comment by maruohon** [comment]
You are missing some commas inside the `worldinfo_onetime` object, after some of the lines (only the last line must not have a comma after itself there). I highly recommend using a text editor with syntax highlighting, and/or an online JSON linter (= syntax/validity checker) if you are not comfortable reading/writing JSON.

The rule of thumb is that all values inside one object (`{}`) or array (`[]`) must be separated by commas, but there must never be a trailing comma after the last value. For easier readability of the config I would also recommend maintaining proper consistent indentation levels, it's far easier to then read it yourself to see where scopes such as objects or arrays start and end and what values belong inside it.

If you need further help with this, I would recommend joining the Discord server, which is linked on the CurseForge page.

**Comment by Kirin92** [comment]
AH! Thank you! I didn't see that! xD thank you so much! I will joining the Discord server!
