### ISSUE TITLE
need some help with creating and loading dimension

### ISSUE THREAD

**Issue by milosrom** [maruohon/justenoughdimensions#69]
first of all i tried this, 
{
  "config_version": {
    "id": "99",
    "version": 0
  },
  "dimensions": [
    {
        "dimensiontype": {
   "id": 99,
   "name": "initialstart2",
   "worldprovider": "WorldProviderSurfaceJED",
   "biome": "minecraft:forest",
 },
            "worldinfo_onetime": {
                "generatorOptions": "3;minecraft:bedrock,64*minecraft:stone,6*minecraft:sandstone,6*minecraft:sand,lake,lava_lake",
     },
    }
  ]
}
and set in jedconfig to be the initialworldspawn. it create the worlds but the configs doesnt aplyes so, i dunnok.
AM Trying to do a single biome dimensions with water lakes, and some sand stone, etc blocks, but without caves and nothing else thana defult forest biome but not flat.

**Comment by maruohon** [comment]
This was answered in CurseForge comments.
